//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNJ_Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_payment_details
    {
        public int p_id { get; set; }
        public string s_name { get; set; }
        public System.DateTime date { get; set; }
        public int amount { get; set; }
        public string transaction_mode { get; set; }
        public string account_holder_name { get; set; }
        public string contact { get; set; }
    }
}
